"""D10-ZF Fourier-Galerkin Hasegawa-Wakatani zonal-flow model.

This module implements the prescribed-zonal-flow branch frozen in decision
D10-ZF.  Radial coupling is generated by projecting the continuous linearized
modified Hasegawa-Wakatani equations onto a periodic Fourier basis at one fixed
nonzero ``k_y``.  No ad-hoc inter-mode coupling or automatic damping is added.

For the state ``z = (phi, eta)`` the returned physical matrices satisfy

``A^H M + M A = 2 kappa Q_Gamma + 2 Q_U - D_C``

up to floating-point roundoff, where ``Q_Gamma`` is the signed outward radial
particle flux and ``Q_U`` is the signed perturbation/mean-flow energy exchange.
Both are inherited from their continuous physical quadratic forms before
truncation.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from numbers import Integral, Real

import numpy as np
import numpy.typing as npt

from nonmodal_flux.core.problem import ArrayLike, TransportProblem

NDArray = npt.NDArray[np.complex128]


def _finite_real(name: str, value: Real) -> float:
    if not isinstance(value, Real):
        raise TypeError(f"{name} must be a real scalar, got {type(value).__name__}.")
    result = float(value)
    if not np.isfinite(result):
        raise ValueError(f"{name} must be finite, got {result}.")
    return result


def _validated_modes(modes: Sequence[Integral] | npt.NDArray[np.integer]) -> np.ndarray:
    values = np.asarray(modes)
    if values.ndim != 1 or values.size == 0:
        raise ValueError("modes must be a nonempty one-dimensional sequence.")
    if not np.issubdtype(values.dtype, np.integer):
        if not np.all(np.equal(values, np.round(values))):
            raise TypeError("modes must contain integers.")
    integer_modes = values.astype(np.int64)
    if len(np.unique(integer_modes)) != len(integer_modes):
        raise ValueError("modes must be unique.")
    return integer_modes


def _validated_profile_coefficients(
    coefficients: Mapping[int, complex],
    *,
    atol: float = 1.0e-14,
) -> dict[int, complex]:
    result: dict[int, complex] = {}
    for raw_q, raw_value in coefficients.items():
        if not isinstance(raw_q, Integral):
            raise TypeError("profile Fourier indices must be integers.")
        q = int(raw_q)
        value = complex(raw_value)
        if not np.isfinite(value.real) or not np.isfinite(value.imag):
            raise ValueError(f"profile coefficient q={q} must be finite.")
        if value != 0.0:
            result[q] = value

    # D10-ZF prescribes a real physical zonal velocity U(x).  Its Fourier
    # coefficients must therefore obey u_{-q} = conj(u_q).
    indices = set(result)
    for q in indices | {-q for q in indices}:
        lhs = result.get(-q, 0.0)
        rhs = np.conj(result.get(q, 0.0))
        if not np.isclose(lhs, rhs, rtol=0.0, atol=atol):
            raise ValueError(
                "profile_coefficients must represent a real U(x): "
                "u[-q] = conj(u[q])."
            )
    return result


def _multiplication_matrix(
    modes: np.ndarray,
    coefficients: Mapping[int, complex],
) -> NDArray:
    return np.array(
        [
            [coefficients.get(int(m - n), 0.0) for n in modes]
            for m in modes
        ],
        dtype=np.complex128,
    )


def _profile_matrices(
    modes: np.ndarray,
    coefficients: Mapping[int, complex],
    fundamental_wavenumber: float,
) -> tuple[NDArray, NDArray, NDArray]:
    u = _multiplication_matrix(modes, coefficients)
    ux = _multiplication_matrix(
        modes,
        {
            q: 1j * fundamental_wavenumber * q * value
            for q, value in coefficients.items()
        },
    )
    uxx = _multiplication_matrix(
        modes,
        {
            q: -(fundamental_wavenumber * q) ** 2 * value
            for q, value in coefficients.items()
        },
    )
    return u, ux, uxx


def hasegawa_wakatani_zonal_flow_matrices(
    *,
    modes: Sequence[Integral] | npt.NDArray[np.integer],
    ky: Real,
    coupling: Real,
    kappa: Real,
    profile_coefficients: Mapping[int, complex],
    fundamental_wavenumber: Real = 1.0,
) -> tuple[NDArray, NDArray, NDArray, NDArray, NDArray]:
    """Return ``(A, M, Q_Gamma, Q_U, D_C)`` for the D10-ZF Galerkin model.

    Parameters
    ----------
    modes:
        Retained integer radial Fourier indices ``m``.  Their physical radial
        wavenumbers are ``k_x = k0 * m``.  The sequence need not be contiguous,
        although centered consecutive sets are the natural convergence family.
    ky:
        Fixed nonzero poloidal wavenumber.
    coupling:
        Resistive Hasegawa-Wakatani coupling ``C >= 0``.
    kappa:
        Background density-gradient parameter ``kappa >= 0``.
    profile_coefficients:
        Fourier coefficients ``u_q`` of the prescribed real zonal velocity
        ``U(x)`` in the same radial basis convention.  Reality is enforced via
        ``u_{-q} = conj(u_q)``.
    fundamental_wavenumber:
        ``k0 = 2 pi / L_x > 0``.  No radial domain length is selected by the
        model constructor itself.

    Notes
    -----
    The basis is orthonormal, so no post-hoc quadrature weights are inserted.
    There is intentionally no damping argument in this D10-ZF assembler: any
    new physical damping model must be introduced by a separate documented
    decision rather than inherited silently from the earlier single-mode pilot.
    """

    mode_values = _validated_modes(modes)
    ky_value = _finite_real("ky", ky)
    coupling_value = _finite_real("coupling", coupling)
    kappa_value = _finite_real("kappa", kappa)
    k0 = _finite_real("fundamental_wavenumber", fundamental_wavenumber)
    coefficients = _validated_profile_coefficients(profile_coefficients)

    if ky_value == 0.0:
        raise ValueError("D10-ZF requires a non-zonal sector: ky != 0.")
    if coupling_value < 0.0:
        raise ValueError("coupling C must be nonnegative.")
    if kappa_value < 0.0:
        raise ValueError("kappa must be nonnegative.")
    if k0 <= 0.0:
        raise ValueError("fundamental_wavenumber must be positive.")

    radial_wavenumbers = k0 * mode_values.astype(float)
    derivative = np.diag(1j * radial_wavenumbers).astype(np.complex128)
    laplacian = np.diag(-(radial_wavenumbers**2 + ky_value**2)).astype(
        np.complex128
    )
    count = len(mode_values)
    identity = np.eye(count, dtype=np.complex128)
    zeros = np.zeros_like(identity)

    u, ux, uxx = _profile_matrices(mode_values, coefficients, k0)

    phi_rhs = (
        -1j * ky_value * u @ laplacian
        + 1j * ky_value * uxx
        + coupling_value * identity
    )
    a_phi_phi = np.linalg.solve(laplacian, phi_rhs)
    a_phi_eta = np.linalg.solve(laplacian, -coupling_value * identity)
    a_eta_phi = (coupling_value - 1j * kappa_value * ky_value) * identity
    a_eta_eta = -coupling_value * identity - 1j * ky_value * u
    generator = np.block([[a_phi_phi, a_phi_eta], [a_eta_phi, a_eta_eta]])

    energy_metric = np.block([[-laplacian, zeros], [zeros, identity]])
    particle_flux = 0.5 * ky_value * np.block(
        [[zeros, 1j * identity], [-1j * identity, zeros]]
    )

    mean_flow_phi = (ky_value / (2j)) * (
        ux @ derivative - (ux @ derivative).conj().T
    )
    mean_flow_exchange = np.block([[mean_flow_phi, zeros], [zeros, zeros]])

    resistive_sink = 2.0 * coupling_value * np.block(
        [[identity, -identity], [-identity, identity]]
    )

    return (
        generator,
        energy_metric,
        particle_flux,
        mean_flow_exchange,
        resistive_sink,
    )


def make_hasegawa_wakatani_zonal_flow_problem(
    *,
    modes: Sequence[Integral] | npt.NDArray[np.integer],
    ky: Real,
    coupling: Real,
    kappa: Real,
    profile_coefficients: Mapping[int, complex],
    fundamental_wavenumber: Real = 1.0,
    B: ArrayLike | None = None,
    Rin: ArrayLike | None = None,
) -> TransportProblem:
    """Construct a validated transport problem targeting physical particle flux.

    ``Q_U`` remains a separate physical balance channel and is therefore not
    merged into the target output.  The returned :class:`TransportProblem`
    uses ``Q = Q_Gamma``.  Call :func:`hasegawa_wakatani_zonal_flow_matrices`
    whenever the separate mean-flow-exchange and resistive-sink matrices are
    required for balance analysis.

    If ``B`` is omitted, the full Galerkin state is admissible.  If ``Rin`` is
    omitted, the natural initial-energy metric ``B^H M B`` is used.
    """

    generator, metric, particle_flux, _, _ = hasegawa_wakatani_zonal_flow_matrices(
        modes=modes,
        ky=ky,
        coupling=coupling,
        kappa=kappa,
        profile_coefficients=profile_coefficients,
        fundamental_wavenumber=fundamental_wavenumber,
    )

    state_dim = generator.shape[0]
    input_map = (
        np.eye(state_dim, dtype=np.complex128) if B is None else np.asarray(B)
    )
    input_metric = (
        input_map.conj().T @ metric @ input_map if Rin is None else np.asarray(Rin)
    )

    return TransportProblem(
        A=generator,
        M=metric,
        Q=particle_flux,
        B=input_map,
        Rin=input_metric,
    )
