"""Finite-horizon operators for accumulated signed transport.

The first implementation covers constant linear dynamics

    x_dot = A x

and computes the finite-horizon state-space operator

    P_Q(T) = integral_0^T exp(A^H t) Q exp(A t) dt,

as well as its projection to the admissible input space. The physical signed
observable ``Q`` remains separate from positive metrics. No whitening,
eigenvalue optimization, or model-specific construction of ``Q`` is performed
in this module.
"""

from __future__ import annotations

from numbers import Real

import jax
import jax.numpy as jnp
import jax.scipy.linalg as jsp_linalg

from nonmodal_flux.core.problem import TransportProblem
from nonmodal_flux.core.propagators import constant_propagator

Array = jax.Array


def accumulated_transport_operator(problem: TransportProblem, T: Real) -> Array:
    """Return the finite-horizon accumulated signed-transport operator ``P_Q(T)``.

    For constant dynamics, the accumulated transport generated by an initial
    state ``x_0`` is

    ``integral_0^T x(t)^H Q x(t) dt = x_0^H P_Q(T) x_0``

    with

    ``P_Q(T) = integral_0^T exp(A^H t) Q exp(A t) dt``.

    The integral is evaluated through a Van Loan block-matrix exponential. If

    ``F = [[A^H, Q], [0, -A]]``

    and the upper-right block of ``exp(F T)`` is ``C(T)``, then

    ``P_Q(T) = C(T) exp(A T)``.

    This construction is valid at finite horizon without assuming that ``A``
    is Hurwitz. ``Q`` may be indefinite.

    Parameters
    ----------
    problem:
        Validated transport problem containing the constant generator ``A`` and
        Hermitian signed observable ``Q``.
    T:
        Finite, non-negative accumulation horizon. Validation is delegated to
        :func:`constant_propagator`.

    Returns
    -------
    jax.Array
        State-space operator ``P_Q(T)``. It is not explicitly symmetrized;
        Hermiticity should follow from the defining integral and is tested
        separately rather than enforced numerically.
    """

    phi = constant_propagator(problem.A, T)
    horizon = float(T)

    a = jnp.asarray(problem.A)
    q = jnp.asarray(problem.Q)
    zero = jnp.zeros_like(a)
    augmented_generator = jnp.block(
        [
            [a.conj().T, q],
            [zero, -a],
        ]
    )

    augmented_propagator = jsp_linalg.expm(augmented_generator * horizon)
    n = a.shape[0]
    cross_block = augmented_propagator[:n, n:]
    return cross_block @ phi


def accumulated_input_transport_operator(problem: TransportProblem, T: Real) -> Array:
    """Return accumulated signed transport projected to admissible inputs.

    With ``x(0) = B u``, the cumulative signed transport is

    ``integral_0^T x(t)^H Q x(t) dt = u^H K_Q^acc(T) u``

    where

    ``K_Q^acc(T) = B^H P_Q(T) B``.

    The result is the raw input-space operator before any whitening by the
    positive input metric ``Rin``. As for ``P_Q(T)``, no explicit
    symmetrization is applied.

    Parameters
    ----------
    problem:
        Validated transport problem containing ``A``, ``Q``, and the admissible
        input map ``B``.
    T:
        Finite, non-negative accumulation horizon.

    Returns
    -------
    jax.Array
        Raw Hermitian cumulative-transport operator in admissible input
        coordinates.
    """

    p_q = accumulated_transport_operator(problem, T)
    b = jnp.asarray(problem.B)
    return b.conj().T @ p_q @ b
